name: CI check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: |
          make lint

      - name: Test & publish code coverage
        run: |
          python -m coverage run -m pytest tests/
          python -m coverage lcov -o coverage.lcov
          mv coverage.xml coverage.lcov reports/
      - name: Upload to QLTY.sh
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: reports/lcov.info

      - name: Verify files
        run: |
          ls -la reports/