name: CI check

on: [push, pull_request]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage pytest PyYAML
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install -e .; fi

      - name: Run tests with coverage
        run: |
          mkdir -p reports
          python -m coverage run -m pytest -v
          python -m coverage lcov -o reports/lcov.info

      - name: Upload coverage to QLty
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: reports/lcov.info
